# Site settings
title: "Focus Beauty"
subtitle: "Your Health Beauty Blog"
tagline: "Discovering and Supporting Sustainable Beauty Products"

# phone: '206.659.8844'
email: "getfocusbeauty@gmail.com"
metaimage: "http://www.getfocusbeauty.com/assets/landing/background/focus-beauty-andrea-ware.jpg"
description: "Currating Sustainable Beauty Products by Andrea Ware. Andrea Ware is a licensed esthetician."
url: "http://www.getfocusbeauty.com" # the base hostname & protocol for your site
google_analytics: "UA-61052500-8"
# feedburner: "github/sqsu"
tinyletter: "focusbeauty"
twitter: getfocusbeauty
instagram: getfocusbeauty
facebook: getfocusbeauty
pinterest: getfocusbeauty
github: focusbeauty

exclude: [node_modules, webpack.config.js]

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
